
import type { Train, Weather, Maintenance, UserPreferences } from './types';

export const initialTrains: Train[] = [
  // Departures from Chennai Central
  {
    id: 'T12007',
    name: 'Shatabdi Express',
    type: 'Express',
    origin: 'Chennai Central',
    destination: 'KSR Bengaluru',
    departureTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 13.0827, lng: 80.2707 },
    route: ['Chennai Central', 'Katpadi', 'Jolarpettai', 'KSR Bengaluru'],
    currentSpeed: 0,
  },
  {
    id: 'T12759',
    name: 'Charminar Express',
    type: 'High-Speed',
    origin: 'Chennai Central',
    destination: 'Hyderabad Deccan',
    departureTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 14 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 13.0827, lng: 80.2707 },
    route: ['Chennai Central', 'Gudur', 'Vijayawada', 'Warangal', 'Secunderabad', 'Hyderabad Deccan'],
    currentSpeed: 0,
  },
    {
    id: 'T12675',
    name: 'Kovai Express',
    type: 'Liner',
    origin: 'Chennai Central',
    destination: 'Coimbatore',
    departureTime: new Date(Date.now() + 0.5 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 13.0827, lng: 80.2707 },
    route: ['Chennai Central', 'Arakkonam', 'Katpadi', 'Salem', 'Erode', 'Coimbatore'],
    currentSpeed: 0,
  },
   {
    id: 'T22671',
    name: 'Tejas Express',
    type: 'High-Speed',
    origin: 'Chennai Egmore',
    destination: 'Madurai',
    departureTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 13.074, lng: 80.262 },
    route: ['Chennai Egmore', 'Tiruchirappalli', 'Dindigul', 'Madurai'],
    currentSpeed: 0,
  },
  // Arrivals to Chennai Central
  {
    id: 'T12640',
    name: 'Brindavan Express',
    type: 'Express',
    origin: 'KSR Bengaluru',
    destination: 'Chennai Central',
    departureTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 12.9716, lng: 77.5946 },
    route: ['KSR Bengaluru', 'Bangarapet', 'Jolarpettai', 'Katpadi', 'Arakkonam', 'Chennai Central'],
    currentSpeed: 95,
  },
   {
    id: 'T12622',
    name: 'Tamil Nadu Express',
    type: 'High-Speed',
    origin: 'New Delhi',
    destination: 'Chennai Central',
    departureTime: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: 'Delayed',
    delay: 45,
    currentLocation: { lat: 28.6139, lng: 77.2090 },
    route: ['New Delhi', 'Agra', 'Bhopal', 'Nagpur', 'Vijayawada', 'Chennai Central'],
    currentSpeed: 115,
  },
  {
    id: 'T12696',
    name: 'TVC-MAS Superfast',
    type: 'Liner',
    origin: 'Thiruvananthapuram',
    destination: 'Chennai Central',
    departureTime: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 8.5241, lng: 76.9366 },
    route: ['Thiruvananthapuram', 'Kollam', 'Ernakulam', 'Coimbatore', 'Katpadi', 'Chennai Central'],
    currentSpeed: 80,
  },
  {
    id: 'CG001',
    name: 'Goods Hauler',
    type: 'Cargo',
    origin: 'Visakhapatnam Port',
    destination: 'Chennai Central',
    departureTime: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    arrivalTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    status: 'On Time',
    delay: 0,
    currentLocation: { lat: 17.6868, lng: 83.2185 },
    route: ['Visakhapatnam Port', 'Vijayawada', 'Gudur', 'Chennai Central'],
    currentSpeed: 60,
  }
];

export const weatherData: Weather[] = [
  { location: 'Katpadi', condition: 'Clear', temperature: 32 },
  { location: 'Vijayawada', condition: 'Thunderstorms', temperature: 28 },
  { location: 'Nagpur', condition: 'Hazy', temperature: 30 },
];

export const maintenanceData: Maintenance[] = [
  {
    trackSegment: 'Gudur -> Vijayawada',
    startTime: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    description: 'Track replacement work.',
  },
  {
    trackSegment: 'Katpadi -> Jolarpettai',
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    endTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    description: 'Signal maintenance work.',
  },
];

export const initialPreferences: UserPreferences = {
  prioritize: 'passenger',
  avoid: ['tunnels'],
};
